name: Deploy to PRODUCTION

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if commit is a merge
        id: mergecheck
        run: |
          git fetch origin main
          MERGE_COMMIT=$(git log -1 --pretty=%P | grep " " || true)
          if [[ -n "$MERGE_COMMIT" ]]; then
            echo "is_merge=true" >> $GITHUB_OUTPUT
          else
            echo "is_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if not a merge commit
        if: steps.mergecheck.outputs.is_merge != 'true'
        run: echo "⛔ Skipping deploy: not a merge commit"

      - name: FTP Deploy to PRODUCTION
        if: steps.mergecheck.outputs.is_merge == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/stunnerboyone.live/
          exclude: |
            .git/
            .git/**
            **/.git/
            **/.git/**
            .github/
            .github/**
            system/**
            image/**
            config.php
            overlord/config.php
