name: Deploy to STAGING

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code from source branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: FTP Deploy to STAGING
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/staging.stunnerboyone.live/
          exclude: |
            .git/
            .git/**
            **/.git/
            **/.git/**
            .github/
            .github/**
            system/**
            image/**
            config.php
            overlord/config.php
